version: '3.2'

services:

  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
  php:
    container_name: my-php
    build: docker/php-fpm
    volumes:
      - ./:/app
      - ./docker/docker-php-ext-xdebug.ini:/usr/local/etc/conf.d/docker-php-ext-xdebug.ini
      - ./storage/log:/data/log
      - ./docker/env.php:/app/env.php
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 9000:9000

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=baohoo
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Asia/Shanghai
  redis:
    image: redis:3
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - 6379:6379
